/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.lxz.proto;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface Mail {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"Mail\",\"namespace\":\"com.lxz.proto\",\"types\":[{\"type\":\"record\",\"name\":\"Message\",\"fields\":[{\"name\":\"to\",\"type\":\"string\"},{\"name\":\"from\",\"type\":\"string\"},{\"name\":\"body\",\"type\":\"string\"},{\"name\":\"status\",\"type\":{\"type\":\"enum\",\"name\":\"MessageStatus\",\"symbols\":[\"NEW\",\"SUCCESS\",\"FAIL\",\"EXCEPTION\"]}}]}],\"messages\":{\"send\":{\"request\":[{\"name\":\"message\",\"type\":\"Message\"}],\"response\":\"Message\"},\"getMessage\":{\"request\":[{\"name\":\"msgId\",\"type\":\"string\"}],\"response\":\"Message\"}}}");
  /**
   */
  com.lxz.proto.Message send(com.lxz.proto.Message message) throws org.apache.avro.AvroRemoteException;
  /**
   */
  com.lxz.proto.Message getMessage(java.lang.CharSequence msgId) throws org.apache.avro.AvroRemoteException;

  @SuppressWarnings("all")
  public interface Callback extends Mail {
    public static final org.apache.avro.Protocol PROTOCOL = com.lxz.proto.Mail.PROTOCOL;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void send(com.lxz.proto.Message message, org.apache.avro.ipc.Callback<com.lxz.proto.Message> callback) throws java.io.IOException;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void getMessage(java.lang.CharSequence msgId, org.apache.avro.ipc.Callback<com.lxz.proto.Message> callback) throws java.io.IOException;
  }
}