/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.lxz.proto;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum MessageStatus { 
  NEW, SUCCESS, FAIL, EXCEPTION  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"MessageStatus\",\"namespace\":\"com.lxz.proto\",\"symbols\":[\"NEW\",\"SUCCESS\",\"FAIL\",\"EXCEPTION\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
